name: mobile_app
description: A new Flutter project.

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+37

environment:
  sdk: ">=2.10.2 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^0.1.3

  # Used for email validation
  email_validator: ^1.0.0

  # Used for sms
  pin_code_fields: ^7.4.0

  # Used for loading indicator
  load: ^1.0.0

  # Used for saving cookies, etc
  shared_preferences: ^0.5.10

  # Used for date formatting
  intl: ^0.17.0

  # Used for transaction history
  grouped_list: ^3.3.0

  # Used for country selection
  country_picker: ^1.0.4

  # Used for http requests
  http: ^0.12.2

  # Used for parsing to sha512
  crypto: ^2.1.5

  # Used for websockets
  web_socket_channel: ^1.1.0

  # Used for JSON :)
  # flutter packages pub run build_runner build --delete-conflicting-outputs
  json_serializable: ^3.4.1

  # Used for beneficiaries searching
  simple_autocomplete_formfield: ^0.3.0

  # Used for camera and images taking
  image_picker: ^0.6.7

  # Used for showing qr-codes
  qr_flutter: ^3.1.0

  # Used for date picking
  flutter_datetime_picker: ^1.5.1

  # Used for pdf
  pdf_flutter: ^1.1.4

  # Used for path taking
  path_provider: ^1.6.11

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner:

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - images/
    - localizations/

  fonts:
    - family: Nunito
      fonts:
        - asset: fonts/Nunito-Regular.ttf
        - asset: fonts/Nunito-Bold.ttf
          weight: 700

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
